SHOW GRANTS FOR CURRENT_USER();

CREATE USER IF NOT EXISTS 'songqueue'@'%' IDENTIFIED BY 'SongQueue2026!';

GRANT ALL PRIVILEGES ON songqueue.* TO 'songqueue'@'%';

FLUSH PRIVILEGES;

SHOW GRANTS FOR 'songqueue'@'%';
